### ISSUE TITLE
Cannot install because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by yangma12** [liaorongfan/DeepPersonality#1]
What is the correct version number please? Below is the error message：

ERROR: Cannot install -r requirements.txt (line 4) and torch==1.9.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested torch==1.9.1
    torchvision 0.8.2 depends on torch==1.7.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by liaorongfan** [comment]
Sorry for the inconvenience, currently I am trying to complete the setup.py file and make pypi installation available.
The version conflict is due to some legacy issues. I solve it manually by:
`$ pip install torchvision==0.8.2 --no-deps`

**Comment by yangma12** [comment]
> 



> 很抱歉给您带来不便，目前我正在尝试完成 setup.py 文件并使 pypi 安装可用。 版本冲突是由于一些遗留问题。我通过以下方式手动解决它： `$ pip install torchvision==0.8.2 --no-deps`
Thank you for your reply, the problem has been solved, can I ask you by the way, do you need to send real international mail to apply for the UDIVA dataset? Or just need an email? I have some doubts after looking at the application requirements for this dataset

**Comment by liaorongfan** [comment]
On its official web https://chalearnlap.cvc.uab.es/dataset/41/description/#
Stated as:

> The UDIVA v0.5 dataset is available upon request. Users will have access to the dataset after the Dataset License has been signed and returned to the dataset administrators. 
> 
> Researchers interested in participating in the [ChaLearn LAP Understanding Social Behavior in Dyadic and Small Group Interactions Challenge at ICCV 2021](http://chalearnlap.cvc.uab.es/challenge/45/description/) may find the Challenge-Oriented Dataset License in the Codalab platform (please, check the instructions [here](http://chalearnlap.cvc.uab.es/challenge/45/description/#getaccess)).
> Researchers interested in using the dataset for research purposes other than the challenge are requested to fill in the [UDIVA v0.5 General-Purpose Dataset License](https://data.chalearnlap.cvc.uab.es/UDIVA_ICCV2021/webpage/UDIVA_v0.5_license.pdf).

And you need to connect the dataset owner following the links provided above
