### ISSUE TITLE
The face extraction is too slow, could you share the processed data?

### ISSUE THREAD

**Issue by youcaiSUN** [liaorongfan/DeepPersonality#4]
Hi,

It costs about 6 min to process a video using provided scripts, which is unacceptable to finish the whole dataset.  Could you share your processed data?

Thanks!

**Comment by liaorongfan** [comment]
Yes, I think it is ok for chalearn 2016 dataset, and I'll uploaded it, but it may take a few days, it's huge

**Comment by youcaiSUN** [comment]
ok, thanks very much!

**Comment by liaorongfan** [comment]
And Glad to know that you are running the code.

**Comment by youcaiSUN** [comment]
Also thanks for the nice code base!

**Comment by liaorongfan** [comment]
Hi, you may find the processed face image data here https://drive.google.com/drive/folders/1UQQVQt5DZxgQPVI1seNbsqiPE436I06K?usp=sharing

**Comment by youcaiSUN** [comment]
Thanks very much! 
By the way, could you also share the processed chalearn 2021 dataset?

**Comment by liaorongfan** [comment]
Sorry, I am afraid not. We are not authorized.  Chalearn 2021  dataset is on request only from its official websit

**Comment by youcaiSUN** [comment]
ok, got it.

**Comment by youcaiSUN** [comment]
It seems that the sample 'xyWpSrfFlQw.004' in the training set of your uploaded face image data does not exist in the annotation file.
