### ISSUE TITLE
the weight of each model

### ISSUE THREAD

**Issue by yangma12** [liaorongfan/DeepPersonality#5]
Hi:
Excuse me, Where can I get the weight of each model? And the following path needs to be created by myself？
_C.WEIGHT = "../results/cr_net/exp4_02-02/checkpoint_48.pkl"

**Comment by liaorongfan** [comment]
Hi , there are so many pretrained models, I will upload the list gradully in weekends, and this cr_net pretrained weights will be uploaded in the comming weekend.

**Comment by liaorongfan** [comment]
Hi, you may find the CRNet pretrained weight in the list now, and the CLI usage file may provide you the info needed

**Comment by liaorongfan** [comment]
Hi, you may find the CRNet pretrained weight in the list now, and the CLI usage file may provide you the info needed

**Comment by yangma12** [comment]
> 您好，您现在可以在列表中找到 CRNet 预训练权重，CLI 使用文件可能会为您提供所需的信息

Thanks a lot, I'll try it later

**Comment by liaorongfan** [comment]
OK, then I will close this ticket. If any question, please feel free to reopen it.
